"""Add database indexes for performance

Revision ID: 59ed8b5a1701
Revises:
Create Date: 2026-02-04 03:05:27.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59ed8b5a1701'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Indexes for foreign keys (faster joins)
    op.create_index(op.f('idx_quips_user_id'), 'quips', ['user_id'], unique=False)
    op.create_index(op.f('idx_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_index(op.f('idx_comments_quip_id'), 'comments', ['quip_id'], unique=False)
    op.create_index(op.f('idx_comments_parent_comment_id'), 'comments', ['parent_comment_id'], unique=False)
    
    # Indexes for composite queries
    # For getting user's quips ordered by creation date
    op.create_index(op.f('idx_quips_user_created'), 'quips', ['user_id', 'created_at'], unique=False)
    
    # For getting comments for a quip (top-level comments ordered by date)
    op.create_index(op.f('idx_comments_quip_parent_created'), 'comments', ['quip_id', 'parent_comment_id', 'created_at'], unique=False)
    
    # For checking if user already upvoted/reposted
    op.create_index(op.f('idx_quip_ups_user_quip'), 'quip_ups', ['user_id', 'quip_id'], unique=False)
    op.create_index(op.f('idx_comment_ups_user_comment'), 'comment_ups', ['user_id', 'comment_id'], unique=False)
    op.create_index(op.f('idx_reposts_user_quip'), 'reposts', ['user_id', 'quip_id'], unique=False)
    
    # Indexes for frequently filtered columns
    # For getting user's reposts ordered by date
    op.create_index(op.f('idx_reposts_user_created'), 'reposts', ['user_id', 'created_at'], unique=False)
    
    # Additional performance indexes
    # For getting comments by user
    op.create_index(op.f('idx_comments_user_created'), 'comments', ['user_id', 'created_at'], unique=False)
    
    # For counting upvotes on quips
    op.create_index(op.f('idx_quip_ups_quip_created'), 'quip_ups', ['quip_id', 'created_at'], unique=False)
    
    # For counting upvotes on comments
    op.create_index(op.f('idx_comment_ups_comment_created'), 'comment_ups', ['comment_id', 'created_at'], unique=False)
    
    # For counting reposts on quips
    op.create_index(op.f('idx_reposts_quip_created'), 'reposts', ['quip_id', 'created_at'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_reposts_quip_created'), table_name='reposts')
    op.drop_index(op.f('idx_comment_ups_comment_created'), table_name='comment_ups')
    op.drop_index(op.f('idx_quip_ups_quip_created'), table_name='quip_ups')
    op.drop_index(op.f('idx_comments_user_created'), table_name='comments')
    op.drop_index(op.f('idx_reposts_user_created'), table_name='reposts')
    op.drop_index(op.f('idx_reposts_user_quip'), table_name='reposts')
    op.drop_index(op.f('idx_comment_ups_user_comment'), table_name='comment_ups')
    op.drop_index(op.f('idx_quip_ups_user_quip'), table_name='quip_ups')
    op.drop_index(op.f('idx_comments_quip_parent_created'), table_name='comments')
    op.drop_index(op.f('idx_quips_user_created'), table_name='quips')
    op.drop_index(op.f('idx_comments_parent_comment_id'), table_name='comments')
    op.drop_index(op.f('idx_comments_quip_id'), table_name='comments')
    op.drop_index(op.f('idx_comments_user_id'), table_name='comments')
    op.drop_index(op.f('idx_quips_user_id'), table_name='quips')
    # ### end Alembic commands ###
